FROM public.ecr.aws/docker/library/python:3.10-slim

WORKDIR /app

COPY . /app/

ARG AWS_REGION
ENV AWS_REGION=${AWS_REGION}

# Print the AWS_REGION for verification
RUN echo "Current AWS Region: $AWS_REGION"

# Install dependencies using the appropriate PyPI source based on AWS region
RUN if [ "$AWS_REGION" = "cn-north-1" ] || [ "$AWS_REGION" = "cn-northwest-1" ]; then \
        pip3 install -r requirements-api.txt -i https://pypi.tuna.tsinghua.edu.cn/simple; \
    else \
        pip3 install -r requirements-api.txt; \
    fi

EXPOSE 8000

ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0"]
